version: '3.0'

services:
  zoo:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    networks: 
      - kafka-network

  kafka-1:
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    networks: 
      - kafka-network
    ports:
      - 9021:9021
    depends_on:
      - zoo
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo:2181 
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # Setting Up Kafka communication
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092, EXTERNAL://0.0.0.0:9021
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:29092, EXTERNAL://localhost:9021
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=EXTERNAL:PLAINTEXT, PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT


networks: 
  kafka-network:
    driver: bridge
