version: '3.0'

services:
  zoo:
    image: zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    networks: 
      - kafka-network

  kafka-1:
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    networks: 
      - kafka-network
    ports:
      - 9021:9021
    depends_on:
      - zoo
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo:2181 
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # Setting Up Kafka communication
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092, EXTERNAL://0.0.0.0:9021
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:29092, EXTERNAL://localhost:9021 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

  kafka-2:
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    networks: 
      - kafka-network
    ports:
      - 9022:9022
    depends_on:
      - zoo
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo:2181 
      - KAFKA_BROKER_ID=2 
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
      # Setting Up Kafka communication
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092, EXTERNAL://0.0.0.0:9022
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:29092, EXTERNAL://localhost:9022, 
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

  kafka-3:
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    networks: 
      - kafka-network
    ports:
      - 9023:9023
    depends_on:
      - zoo
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo:2181 
      - KAFKA_BROKER_ID=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
      # Setting Up Kafka communication
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092, EXTERNAL://0.0.0.0:9023
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3:29092, EXTERNAL://localhost:9023
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL


networks: 
  kafka-network:
    driver: bridge
