version: '3.0'

services:
  zoo:
    volumes: # Production purpose 
      - /home/ylee/data/zookeeper/data:/var/lib/zookeeper/data
      - /home/ylee/data/zookeeper/log:/var/lib/zookeeper/log

  kafka-1:
    volumes: # Production purpose 
      - /home/ylee/data/kafka1:/var/lib/kafka/data 
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:29092, EXTERNAL://anomalies-detection.ai.moneylion.com:9021

networks: 
  kafka-network:
    driver: bridge
